### ISSUE TITLE
The method size() returns None on some resources, even in cases where there's nothing preventing it to be calculated

### ISSUE THREAD

**Issue by wspringer** [jesseeichar/scala-io#13]
Example:

```
Resource.fromFileString(...).size // Returns None
```

In this particular case, it seems perfectly fine to return a Some. In other cases, there might not be an efficient way to calculate the size. In fact, in those cases, the only option (no pun intended) would be to traverse the entire stream. But still, even my own code would have to do that. If I really feel I need the size, it apparently is the pain I will have to bear.

In this case, I would plea for copying the policy of the Scala collections API. In those cases, size is always returned, even if it comes with a price.

**Comment by jesseeichar** [comment]
This is an oversight.  The intention was to have resources like this return a size.  But size must be an option (in my opinion) because in some cases a Resource can only be traversed a single time.  For example if the resource was a input stream passed from an outside source.  

I can see the argument for a parameter force the calculation, in which case the return would traverse the entire resource.

**Comment by wspringer** [comment]
> I can see the argument for a parameter force the calculation, in which case the return would traverse the entire resource.

... or fail with an exception, I guess.

**Comment by wspringer** [comment]
Whoops, closed the issue unintentionally. My bad. I guess we need to reopen it.

**Comment by jesseeichar** [comment]
Reopened.  :) no harm done

**Comment by jesseeichar** [comment]
Fixed as of 17b0f70f1e70a9b0d776dae24771abefcc4e9d80
