### ISSUE TITLE
LongSeqView instead of LongTraversableView

### ISSUE THREAD

**Issue by wspringer** [jesseeichar/scala-io#17]
I expect bytes from a file to be ordered at all times. That would call for a SeqView rather than a TraversableView. That would in fact also take care of my problem to compare the size of two Input objects. I could just test the `bytes` views of both objects for equality.

**Comment by jesseeichar** [comment]
The main problem for me is that Seq has iterator methods.  An iterator is not safe with regards to resources.

I see three options:
- Implement Seq but throw exceptions if an iterator method is called.  This is going to be tricky because I would not be surprised if several methods in Seq are implemented in terms of iterator.  At the least it is not nice because you lose type safety with regards to iterator.
- Add methods to LongTraversableView.  Good in many ways but it is not a Seq so cannot be passed to objects that take a Seq.  Also code reuse could be problematic
- Leave it as is.  

I think we will hold on this issue as it is a big design issue and see if other people have opinions on it.

I suppose the biggest question is what are the exact use-cases where Seq is needed and is solution 2 sufficient?  It is pretty easy to add apply and many other Seq functions.  It is mainly the iterator that is an issue for me.

**Comment by wspringer** [comment]
Can you give an example explaining the problems we would encounter when having an iterator method?

**Comment by jesseeichar** [comment]
For example:

```
val firstByte = Path("file").bytes.iterator.next
```

Left like that it is a resource leak because we cannot close the iterator since we don't know if the program is going to request the next item in the iterator.  The only way that code could work would be to add a timeout which automatically closes the iterator, which  would likely lead to many hard to detect bugs.

**Comment by wspringer** [comment]
Slapping myself on the head. You are totally right.

Option 1 definitely not the way to go.

**Comment by jesseeichar** [comment]
I have settled on adding several sequence methods like apply, indexOf, etc...  Some of the methods are difficult to impossible to do so they are not implemented (dropRight for example)  It is possible to add some of them later but until I have some emphatic requests I will wait on them.

I have committed those changes on and around commit 7557eb540959d0a9b2ce
