### ISSUE TITLE
Inefficient detection of line termination

### ISSUE THREAD

**Issue by jorgeortiz85** [jesseeichar/scala-io#39]
I have a script that needs to read some files (~20 files of ~1000 lines each). I recently ported it from using Scala 2.8.1's Source.getLines to scala-io 1.1's Path.lines(includeTerminator = false). I noticed a substantial slowdown in the runtime of my script after this transition.

Some quick profiling shows that the vast majority of the time is being spent in the 'split' method of Line.Terminators.Terminator.

If I understand the interaction between LineTraversable and Terminator correctly, Terminator needs to do an O(N) scan through the Seq[Char] that it is passed in order to search for a line terminator, and LineTraversable passes it a new and growing Seq[Char] for every additional character that it sees (effectively, it passes O(N) different Seq[Char]s for each line it reads). If a line is N lines long, the first character in the line will be processed N^2 times.

**Comment by viktorklang** [comment]
Sexy indeed

**Comment by jesseeichar** [comment]
I agree.  That code is actually a direct ripoff from and old version of Source and I have obviously not spent any time optimizing it, as with many parts of the library.  I am in the process of writing performance tests based on Josh's sperformance so that I can track the performance of various parts of the library.  

If you have a good algorithm for line detection I would love to see a reference to it.

Thanks 

Jesse

**Comment by jesseeichar** [comment]
I suppose I can look at the recent Source.getLines implementation.  I have been finding that many of the performance slowdowns are related to not using enough while loops.  the trunk version has already seen some pretty big performance improvements.

**Comment by jesseeichar** [comment]
Now using Source.getLines implementation.  The performance is drastically improved.  However there are still improvements required for raw inputstream reading but I am working on that.  That is a little more difficult.
