### ISSUE TITLE
Any plans to support ZIP-filesystem?

### ISSUE THREAD

**Issue by ysae** [jesseeichar/scala-io#63]
I saw that zipfs was already removed from this project in the gitorious repository [diff](https://gitorious.org/j-random-crap/io/commit/d764ebe5007ae04f3345ffc4b382ed2ad935cc8b/diffs).
It means that zip filesystem will not be a part of this project in the future?

**Comment by jesseeichar** [comment]
I was working on it mainly so that I could understand the different
requirements for implementing filesystems.  Lately I am playing with Java 7
implementation and it has a zipfs implementation already and I am satisfied
with using their SPI API for creating plugins.  I am almost done doing a
RAMFS (alpha) implementation using that API and it is acceptable.

Jesse
